In [115]:
import numpy as np
import pandas as pd

In [116]:
df = pd.read_csv("airbnb_v1.csv")

C:\Users\apoor\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (0,2,10,12) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [117]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,NaN,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,NaN,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,NaN,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,NaN,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,90

In [118]:
df.columns = df.iloc[0]
df

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,NaN,price
0,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,NaN,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,NaN,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,NaN,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,NaN,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,90

In [119]:
df = df.iloc[1:]
df

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,NaN,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,NaN,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,NaN,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,NaN,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,First Floor,56.05427828,NaN,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,NaN,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,NaN,90

### The first row has been converted to column names.

In [120]:
df = df.loc[:, df.columns.notna()]
df

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,First Floor,56.05427828,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,90

### Removed the NaN Column

In [122]:
#df[' noise.dB'] = df[' noise.dB'].str.replace("dB","")

In [123]:
df['price'] = df['price'].str.replace("approx","")
df

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,$225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,First Floor,56.05427828,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,90

In [124]:
df['price'] = df['price'].str.replace("$","")
df['price'] = df['price'].str.replace("open to negotiate","")
df['price'] = df['price'].str.replace("deal price","")
df['price'] = df['price'].str.replace("/- only","")
df['price'] = df['price'].str.replace(",","")
df

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69.0564645654522dB,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56.0542782840785dB,225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56.0542782840785dB,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69.0564645654522dB,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,First Floor,56.05427828,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69.0564645654522dB,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69.0564645654522dB,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56.0542782840785dB,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56.0542782840785dB,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56.0542782840785dB,90

In [125]:
df['price'] = df['price'].astype(int)

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

### Converted the prices to integers

In [126]:
df['noise.dB.'] = df['noise.dB.'].str.replace("dB","")

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [127]:
df['noise.dB.'] = df['noise.dB.'].astype(float)
df['noise.dB.'] = df['noise.dB.'].round()
df['noise.dB.'] = df['noise.dB.'].astype(int)
df

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,First Floor,69,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,First Floor,56,225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,First Floor,56,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,First Floor,69,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,First Floor,56,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,First Floor,69,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,First Floor,69,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,First Floor,56,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,First Floor,56,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,First Floor,56,90

### Noise converted to int

In [128]:
floor_values = df['floor'].unique()
print(floor_values)

df['floor'] = df['floor'].str.replace("First Floor", '1')

df['floor'] = df['floor'].str.replace("Fifth Floor", '5')
df['floor'] = df['floor'].str.replace("Fourth Floor", '4')

df['floor'] = df['floor'].str.replace("Second Floor", '2')

df['floor'] = df['floor'].str.replace("Third Floor", '3')

df['floor'] = df['floor'].str.replace("Sixth Floor", '6')
df['floor'] = df['floor'].str.replace("Seventh Floor", '7')

df['floor'] = df['floor'].str.replace("Eighth Floor", '8')

df['floor'] = df['floor'].str.replace("Ninth Floor", '9')

df['floor'] = df['floor'].str.replace("Tenth Floor", '10')

df['floor'] = df['floor'].str.replace("Eleventh Floor", '11')

df['floor'] = df['floor'].str.replace("1st-Floor", '1')
df['floor'] = df['floor'].str.replace("5th-Floor", '5')
df['floor'] = df['floor'].str.replace("Hundredth Floor", '100')
df['floor'] = df['floor'].str.replace("Seventeenth Floor", '17')
df['floor'] = df['floor'].str.replace("Sixteenth Floor", '16')
df['floor'] = df['floor'].str.replace("Twentieth Floor", '20')

df['floor'] = df['floor'].str.replace("1st-floor", '1')
df['floor'] = df['floor'].str.replace("5th Floor", '5')
df['floor'] = df['floor'].str.replace("Hundreth Floor", '100')
df['floor'] = df['floor'].str.replace("Thirteenth Floor", '13')
df['floor'] = df['floor'].str.replace("Lower Level", '-1')



df

['First Floor' '1' 'Fifth Floor' '1st-floor' '5th Floor' '2' '5'
 'Fourth Floor' 'Second Floor' 'Third Floor' 'Tenth Floor' 'Eighth Floor'
 'Eleventh Floor' 'Seventh Floor' 'Sixth Floor' 'Hundreth Floor' '0'
 'Sixteenth Floor' '20' '12' 'Seventeenth Floor' '8' 'Lower Level'
 'Ninth Floor' 'Twentieth Floor' '16' 'Thirteenth Floor' '17' '15' '14']

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,1,69,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,1,56,225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,NaN,NaN,1,56,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,1,69,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,1,56,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,NaN,NaN,1,69,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,NaN,NaN,1,69,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,NaN,NaN,1,56,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,NaN,NaN,1,56,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,NaN,NaN,1,56,90

### Floors Done

In [129]:
df['last review (date)'].fillna('1950-01-01', inplace=True)
df['reviews per month'].fillna('0', inplace=True)

df

C:\Users\apoor\anaconda3\lib\site-packages\pandas\core\generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,1,69,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,1,56,225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902N,-73.9419,Private room,3,0,1950-01-01,0,1,56,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514N,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,1,69,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,1,56,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,1950-01-01,0,1,69,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317° W,Private room,4,0,1950-01-01,0,1,69,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,1950-01-01,0,1,56,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,1950-01-01,0,1,56,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,1950-01-01,0,1,56,90

### Reviews NaN done

In [130]:
df['longitude'] = df['longitude'].str.replace("W","")
df['longitude'] = df['longitude'].str.replace("°","")

df['latitude'] = df['latitude'].str.replace("N","")
df['latitude'] = df['latitude'].str.replace("°","")
df

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,id,name,host id,[host_name],neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,1,69,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,1,56,225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.9419,Private room,3,0,1950-01-01,0,1,56,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,1,69,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,1,56,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,1950-01-01,0,1,69,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,4,0,1950-01-01,0,1,69,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,1950-01-01,0,1,56,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,1950-01-01,0,1,56,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,1950-01-01,0,1,56,90

### Latitude and Longitude

In [132]:
df.rename(columns={"[host_name]":"host_name"}, inplace = True)

df

C:\Users\apoor\anaconda3\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,id,name,host id,host_name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,1,69,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,1,56,225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.9419,Private room,3,0,1950-01-01,0,1,56,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,1,69,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,1,56,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,1950-01-01,0,1,69,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,4,0,1950-01-01,0,1,69,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,1950-01-01,0,1,56,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,1950-01-01,0,1,56,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,1950-01-01,0,1,56,90

### Latitude and Longitude done

In [133]:
print(df['neighbourhood'].isna().sum())
print(df['neighbourhood group'].isna().sum())
print(df['host_name'].isna().sum())
print(df['name'].isna().sum())
print(df['minimum nights'].isna().sum())

30
0
16
416
0

In [134]:
df.dropna(inplace = True)
df

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,id,name,host id,host_name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,1,69,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,1,56,225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.9419,Private room,3,0,1950-01-01,0,1,56,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,1,69,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,1,56,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,1950-01-01,0,1,69,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,4,0,1950-01-01,0,1,69,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,1950-01-01,0,1,56,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,1950-01-01,0,1,56,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,1950-01-01,0,1,56,90

In [137]:
df['minimum nights'] = df['minimum nights'].str.replace("nights", "")
df['minimum nights'] = df['minimum nights'].str.replace(" ", "")
df

C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\apoor\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,id,name,host id,host_name,neighbourhood group,neighbourhood,latitude,longitude,room and type,minimum nights,number of reviews (total),last review (date),reviews per month,floor,noise.dB.,price
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn - **Borough**,KensingtonBrooklyn - **Borough**-Brooklyn - **...,40.64749,-73.97237,Private room,1,9,2018-10-19,0.21,1,69,149
2,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,1,45,2019-05-21,0.38,1,56,225
3,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.9419,Private room,3,0,1950-01-01,0,1,56,150
4,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,1,270,2019-07-05,4.64,1,69,89
5,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,10,9,2018-11-19,0.1,1,56,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39114,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,2,0,1950-01-01,0,1,69,70
39115,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,4,0,1950-01-01,0,1,69,40
39116,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,10,0,1950-01-01,0,1,56,115
39117,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,1,0,1950-01-01,0,1,56,55
39118,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,7,0,1950-01-01,0,1,56,90

KeyError: 2857312914440